Added PHP7 type declarations and added comments to methods &variables
guhelski/kent-beck-tdd-php pull request #2
Opened 2017-06-17 19:47 UTC by LoganConnor44

2017-06-17 20:07 UTC, LoganConnor44 commented
It looks as if this continuous integration check failed due to only testing php4-5.

This would be expected because the type declarations used were introduced in 7

2017-06-19 09:48 UTC, guhelski commented on src/TDD/Chapter2/Dollar.php
> +	 * @var int $amount	The monetary amount given to the dollar object
Extra spaces.

2017-06-19 09:48 UTC, guhelski requested changes

2017-06-19 09:48 UTC, guhelski commented on tests/TDD/Chapter2/Chapter2Test.php
> +	 * Tests that the object $product's method amount returns the expected value
Same here.

2017-06-20 07:09 UTC, guhelski approved these changes

2017-06-20 07:09 UTC, merged