Chapter4
guhelski/kent-beck-tdd-php pull request #4
Opened 2017-06-17 20:54 UTC by LoganConnor44

2017-07-02 02:50 UTC, LoganConnor44 commented
Please take a moment at your earliest convenience to review the passing branches. If there is something you would like changed, let me know.

2017-07-03 13:32 UTC, guhelski commented on src/TDD/Chapter4/Dollar.php
> +	/**
Extra space.

2017-07-03 13:32 UTC, guhelski commented on src/TDD/Chapter4/Dollar.php
> +	/**
Same here.

2017-07-03 13:33 UTC, guhelski commented on src/TDD/Chapter4/Dollar.php
> +	/**
Same here.

2017-07-03 13:33 UTC, guhelski commented on src/TDD/Chapter4/Dollar.php
> +	/**
Same here.

2017-07-03 13:34 UTC, guhelski requested changes
Minor formatting issues, extra spaces in the docblocks.

2017-07-03 20:50 UTC, LoganConnor44 commented
It seems that Sublime's indent / spaces does not play nicely with github.

The spacing issues have been fixed for this branch.

2017-07-04 07:22 UTC, merged